version: '3.8'

services:
  db:
    platform: linux/x86_64
    image: percona
    container_name: Database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=HSModelaje_db
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=laravel_password
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - laravel-exa

  main:
    container_name: Serve
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: HSModelaje_db
      DB_USERNAME: root
      DB_PASSWORD: root
    networks:
      - laravel-exa

    command: >
        sh -c "while ! nc -z db 3306; do sleep 5; done &&
        cp .env.example .env &&
        php artisan key:generate &&
        php artisan migrate:fresh --seed --force &&
        php artisan serve --host=0.0.0.0"

  queue:
    container_name: Queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'php artisan queue:work'
    depends_on:
      - db
    networks:
      - laravel-exa

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: PhpMyAdmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - laravel-exa

  mailpit:
    image: axllent/mailpit
    container_name: MailPit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel-exa

networks:
  laravel-exa:
    driver: bridge

volumes:
  db:
    driver: local
